sudo: required
services:
  - docker
language: python
python:
  - 3.6
env:
  - COMPOSE_FILE=docker-compose.travis.yml

install:
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-ce
  - sudo pip install docker-compose

before_script:
  - docker version
  - docker-compose --version

script:
  - docker-compose build --pull
  - docker-compose up -d
  - sleep 5
  - docker-compose logs web
  - docker-compose exec web py.test --pylama
  - docker-compose run web pipchecker -r ../requirements.txt
