version: "3"

services:
  web:
    build: .
    command: "runserver 0.0.0.0:8000"
    environment:
        PYTHONUNBUFFERED: 0
        DJANGO_SETTINGS_MODULE: feinstaub.settings.test
    entrypoint:
     - './manage.py'
    links:
     - db
    depends_on:
      - db
  db:
    image: postgres:9.6
